### ISSUE TITLE
Bones are disconnected

### ISSUE THREAD

**Issue by Tosyk** [dingdio/Witcher3-Blender-Tools#2]
Hello, I really appreciate for the tool! It's really helpful.

However, I have an issue - the bones are disconnected if load from w2mesh, w2ent.
Only if I load w2rig I have an option to connect bones. But it's hard to say what rig the model is using. So, I usually load w2ent files and get bones disconnected.

Please help me

**Comment by dingdio** [comment]
The bones are disconnected by design in w2mesh files. Only the w2rig has the hierarchy data.

If you use the "Import Character" button in the n-Panel you can load a character or monster .w2ent and it will attach the w2mesh to the w2rig automatically. You can also use "Add Constraints" to manually attach a mesh to be driven by a rig.
The character tab will also show what rigs are being used.
![Deer](https://i.imgur.com/SGD8JDM.jpeg)

Alternatively you can just merge the both the mesh and rig together into a single armature.

**Comment by Tosyk** [comment]
For some reason I don't use n-panel. thank you :p
